apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helmcharts.cattle.io/managed-by: helm-controller
  generation: 1
  name: kyverno-install
  namespace: default
spec:
  version: 3.4.4
  chart: kyverno
  repo: https://kyverno.github.io/kyverno/
  failurePolicy: abort
  targetNamespace: kyverno
  createNamespace: true
  valuesContent: |-
    admissionController:
      replicas: 3
    backgroundController:
      replicas: 3
    cleanupController:
      replicas: 3
    reportsController:
      replicas: 3
